- hosts: localhost
  tasks:
  - name: Install a yum package - java, git and maven
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - java-1.8.0-openjdk
    - git
    - maven
  - name: Download jenkins.repo
    get_url:
     url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
     dest: /etc/yum.repos.d/jenkins.repo
  - name: Import Jenkins Key
    rpm_key:
     state: present
     key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  - name: Install Jenkins
    yum:
     name: jenkins
     state: present
  - name: Start & Enable Jenkins
    systemd:
     name: jenkins
     state: started
     enabled: true
  - name: Sleep for 30 seconds and continue with play
    wait_for: timeout=30
  - name: Get init password Jenkins
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    changed_when: false
    register: result
  - name: Print init password Jenkins
    debug:
     var: result.stdout
- hosts: artifactory
  remote_user: ec2-user
  become: true
  tasks:
  - name: Install a yum package - java, jfrog
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - java-1.8.0-openjdk
    - https://bintray.com/jfrog/artifactory-rpms/download_file?file_path=jfrog-artifactory-oss-4.12.2.rpm
  - name: Start service jfrog artifactory, if not started
    service:
      name: artifactory
      state: started
- hosts: sonar
  remote_user: ec2-user
  become: true
  tasks:
  - name: Install a yum package - java, sonar
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - java-1.8.0-openjdk
    - https://sourceforge.net/projects/sonar-pkg/files/rpm/noarch/sonar-4.5-1.noarch.rpm
  - name: Start service sonar, if not started
    service:
      name: sonar
      state: started
